version: "3.5"

x-logging:
  &default-logging
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

networks:
  dotnetdemo-net:
    name: dotnetdemo-net

services:
  dotnetdemo-app:
    container_name: dotnetdemo-app
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    logging: *default-logging
    restart: always
    working_dir: /app
    environment:
      - TZ=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    command: dotnet watch run
    volumes:
      - ./src:/app
    networks:
      dotnetdemo-net:
        aliases:
          - app.container.local

  dotnetdemo-nginx:
    container_name: dotnetdemo-nginx
    image: nginx:1.16
    logging: *default-logging
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./dev:/storage:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/nginx/ssl:/ssl:ro
    networks:
      dotnetdemo-net:
        aliases:
          - dotnetdemo.test
    ports:
      - 80:80

  dotnetdemo-mariadb:
    container_name: dotnetdemo-mariadb
    image: mariadb:10.3.20-bionic
    logging: *default-logging
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - dotnetdemo-mariadb:/var/lib/mysql
    networks:
      dotnetdemo-net:
        aliases:
          - mariadb.container.local

  dotnetdemo-phpmyadmin:
    container_name: dotnetdemo-phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    logging: *default-logging
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - PMA_HOST=mariadb.container.local
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=/phpmyadmin/
    networks:
      dotnetdemo-net:
        aliases:
          - phpmyadmin.container.local
    depends_on:
      - dotnetdemo-mariadb

  dotnetdemo-vscode:
    container_name: dotnetdemo-vscode
    build:
      context: ./.docker/vscode
      dockerfile: Dockerfile
    image: vscode:latest
    logging: *default-logging
    restart: always
    command: /home/coder/project
    environment:
      - TZ=Asia/Bangkok
      - PASSWORD=1234
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/vscode/settings.json:/home/coder/.vscode/User/settings.json
      - ./:/home/coder/project
    networks:
      - dotnetdemo-net
    ports:
      - 8080:8080

volumes:
  dotnetdemo-mariadb:
    name: dotnetdemo-mariadb
